// Firebase configuration is handled by firebase_options.dart (generated by FlutterFire CLI).
// This file only exposes non-Firebase secrets that must be injected via --dart-define at build time.
// Never add hardcoded keys here.
class SecureConfig {
  SecureConfig._();

  // Inject at build time: flutter run --dart-define=ANTHROPIC_API_KEY=sk-ant-...
  static const String anthropicApiKey =
      String.fromEnvironment('ANTHROPIC_API_KEY');

  static bool get hasAnthropicKey => anthropicApiKey.isNotEmpty;
}
